### ISSUE TITLE
[HU1] Subir y generar horarios

### ISSUE THREAD

**Issue by morevi** [morevi/jobcontrol#3]
Como empleado, quiero que cada semana el sistema genere mi horario, a partir de un horario base introducido anteriormente, y me permita su modificación y confirmación. De forma que pueda reutilizarse y ahorrar tiempo.

**Comment by JJ** [comment]
"Generar el horario" es una tarea del programador. No está en el "espacio del problema". Una HU debe de estar relacionada con la lógica de negocio y hablar de un beneficio para el usuario. En general, todas las HUs aquí parecen issues más que HUs, porque todas hablan de lo que los proramadores tendrían que hacer.

**Comment by JJ** [comment]
Dos cosas
1. Que no sea una HU no quiere decir que no sirve. Por favor, trata de entender la diferencia entre un issue y una HU
2. Si no cierras con commit te dará error en los siguientes objetivos al entregarlos.

**Comment by morevi** [comment]
1. He estado estudiando sobre HUs, épicas y todo el tema, y como básicamente las he vuelto a reescribir, estaba tratando de hacer limpieza y empezar de "cero". [Aquí están las nuevas HU](https://github.com/morevi/jobcontrol/blob/objetivo-1/docs/planificacion.md#%C3%A9picas-e-historias-de-usuario), por si quieres echarle un ojo (qué no deberias ya que no entrego aún) antes de que me ponga a reacer las issues HU y Milestones.
2. ¿Dará error aunque abra nuevas HUs? En ese caso creo que las abriré todas y luego las cerraré con un commit de "limpieza".
