### ISSUE TITLE
Almacenar un recuento de las horas trabajadas de un usuario

### ISSUE THREAD

**Issue by eantoniocalo18** [morevi/jobcontrol#41]
Como programador necesito definir una estructura de datos que registre las horas trabajadas por un usuario. 
Con respecto a las horas trabajadas de un usuario tenemos la siguiente información:
- El usuario apunta de manera manual todos los días y horas que trabaja
- La información relativa a los horarios del usuario la tendrá que incluir posteriormente en un EXCEL
- El usuario tiene que trabajar una cantidad determinada de horas en un proyecto a la semana. Estas horas son acumulativas, si trabaja más horas de lo estipulado la semana siguiente tendrá que trabajar menos y viceversa.
- Los cargos superiores recogen la información de estos horarios para comprobar el grado de cumplimiento de los horarios y el desempeño en el proyecto.

Por lo tanto se ve la necesidad de crear una clase Horario donde se almacenarán los datos relativos a las horas trabajadas por un usuario, así como sus horas adelantadas y atrasadas (según M0).
Esta clase estará compuesta por:
- Atributos: fecha de inicio, nombre del usuario que lo realiza y horas trabajadas
- Métodos: obtener las horas trabajadas y pasar los datos a formato CSV

**Comment by JJ** [comment]
¿De dónde sale de aquí que tiene que haber una clase que se llame Horario y que incluya un id? ¿Para qué sirve el ID?
